# Generated by Django 6.0.1 on 2026-01-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_payment_course_payment_pidx_sponsorship_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='pidx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
